- bin/compare_html
- bin/compare_json
- bin/generate_pages
- bin/write_cross_performance_tables
- install_software.sh
- lib/encoder.py
- lib/encoder_unittest.py
- lib/mpeg_settings.py
- lib/score_tools.py
- lib/score_tools_unittest.py
- lib/visual_metrics.py
- lib/visual_metrics_unittest.py
- video/get-stuff
- website/assets/js/codecfuncs.js
- website/index.md
- website/results/index-new.md
- website/results/index.md
- website/results/show_result.md
Redesigning the interface between the website parts and the Python backend parts to interchange JSON files instead of generating HTML files.
This makes for a simpler system, where display is handled on the display side, and only data is handled on the backend side.
> Json result storage

- lib/encoder.py
- lib/encoder_unittest.py
- lib/optimizer.py
- lib/optimizer_unittest.py
- lib/vp8_mpeg.py
- lib/vp8_mpeg_1d.py
- lib/vp9.py
This change makes the optimizer aggressively remove parameters, and gives
slightly higher scores (0.000001 dB per parameter) for shorter parameter
lists, leading the optimizer to prefer them.
It adds a function for marking parameters as mandatory, since some codecs
function very badly with all parameters removed.
Addresses #4 .
> Add functions for removing parameters when trying new configurations.

- bin/generate_pages
- lib/encoder.py
- lib/encoder_unittest.py
- lib/pick_codec.py
- lib/x264_baseline.py
- lib/x264_unittest.py
This adds measurements for the "baseline" configuration of H.264
to the tables. It also separates the list of codecs for the RT
mode and the PSNR mode comparision, so that we can make them
different when we need to.
> Adding X264 baseline codec.

- lib/encoder.py
- lib/encoder_unittest.py
Also adds an unit test for checking that the error is actually thrown
for the wrong-checksum case.
> Adds more info to two error messages for broken stored configs.

- bin/force_run_config
- lib/encoder.py
- lib/encoder_unittest.py
This speeds up result parsing considerably, as well as using a more
standard format for storage - important when one shares results.
Also moves a requirement on enoding time due to testing on a slow
computer.
> Changes the storage format for results from Python literals to JSON.

- bin/generate_pages
- bin/show_versions
- compile_tools.sh
- install_software.sh
- lib/encoder.py
- lib/ffmpeg.py
- lib/hevc_jm.py
- lib/hevc_jm_unittest.py
- lib/mjpeg.py
- lib/mjpeg_unittest.py
- lib/pick_codec.py
- lib/test_tools.py
- lib/x265.py
- lib/x265_unittest.py
This PR adds the X265 and HEVC implementations of the HEVC (H.265) codec.
Neither codec has parameters that can vary yet.
Reporting exposes only the X265 codec so far.
Note - there is a bug in ffmpeg's decoding of HEVC files that sometimes
produces the wrong number of frames - as a stopgap measure, the decoder
from the HEVC Reference Model is used.
> Adding two HEVC codecs, reporting on one of them.

- .pylint.rc
- bin/run_all_tests
- lib/optimizer.py
- lib/optimizer_unittest.py
This extends FilesAndRates to optionally check for whether files exist,
and omit files from the fileset that do not exist on the disk. This allows
testing the code without having a copy of all the files.
Also starts updating the pylint checker to a new version of pylint (1.1),
which does a lot more checking. Not all errors suppressed yet.
> Adds running tools without all YUV files in a fileset.

- .pylint.rc
- bin/compare_codecs
- bin/list_best_results
- lib/fileset_picker.py
- lib/fileset_picker_unittest.py
- lib/test_tools.py
- website/contributing/index.md
This adds a picker for filesets, with MPEG being treated specially,
and others having rates picked from a decision tree.
Filesets are directories under "video".
Also suppressed a new warning that appeared with pylint 1.4.1.
> Multiple filesets support.

- bin/rewrite_ast_as_json
- lib/vp9.py
- lib/vp9_unittest.py
This allows 1-pass and 2-pass to be exercised explicitly.
Also fix some pylint errors in a hack script submitted earlier.
> Add a "passes" parameter to the VP9 encoder

- bin/randomly_improve_encoding
- lib/mjpeg.py
- lib/mjpeg_unittest.py
This change ensures that qmax is always >= qmin when both are
specified for the mjpeg codec. It also ensures that qmax is given
if qmin > 31 (seems to be the hidden default for qmax).
It also adds a --dry-run flag to the randomly_improve_encoding script,
and the ability to randomly improve only for a single codec.
> Fixes qmin / qmax relationship on the mjpeg codec.

- lib/openh264.py
1, Suggest not to use the options -maxbrTotal and -lmaxb in performance tests like this, since these two will put stricter control on bit rate. Given the focus of openh264 is more on paced vbr, suggest not to use these constrictions in performance testing. Setting them to 0 which mean unspecified if there is no need to set them.
2, '-fs 0' can be used to disable EnableFrameSkip, regarding that this is PSNR test I use a constant here.  Seems there is no such variable in 'parameters'? Pls let me know if I should use a variable for this rather than a constant. Thx.
> use the recommended command options for openh264

- AUTHORS
- CONTRIBUTORS
- compile_tools.sh
- lib/openh264.py
about the new options: 
disabling temporal layer settings which is mainly for error robustness; tested with some sequences in webm fileset and the score seemed increased.
> Update docs needed and suggest new options on frame rate and other setting of OpenH264

- bin/vary_parameter
- lib/encoder.py
- lib/encoder_unittest.py
- lib/file_codec.py
- lib/file_codec_unittest.py
- lib/x264.py
- lib/x264_unittest.py
This adds a parameter for controlling the number of threads to
the x264 codec, removing the previously hardcoded default.
NOTE: WILL INVALIDATE STORED ENCODES.
It also adds a new tool "vary_parameter" that lets one run encodes
for all possible values of a parameter, so that response curves
can be seen.
It also fixes a minor Lint error in openh264.py.
> Add "--threads" parameter to x264 codec.

- .travis.yml
- bin/pylint
- bin/run_all_tests
- install_software.sh
This PR adds a Travis CI configuration, and modifies the
install_software and run_all_tests scripts in such a way that
the Travis CI tests can run without compiling binaries.
Compiling is possible under Travis, but it takes a long time;
tests should be fast.
Bugs were found and fixed.
> Travis build activation: Travis file and test fixes.

- bin/run_all_tests
- bin/run_all_tools
- bin/sensitivity_analysis
- bin/vary_parameter
- bin/verify_stored_parameters
- lib/encoder.py
- lib/encoder_unittest.py
- lib/file_codec.py
- lib/mjpeg_unittest.py
- lib/optimizer_unittest.py
- lib/x264.py
- lib/x264_baseline.py
- lib/x264_realtime.py
This makes configurations with:
- Missing mandatory options
- Options with undefined values
return error when one attempts to parse them.
Unrecognized parameters are still allowed.
The "verify_hashnames" script has been renamed to
"verify_stored_parameters" and changed a bit to reflect that it
also checks that parameters can be parsed.
> Make bad configurations cause errors.

- bin/rewrite_ast_as_json
- bin/verify_stored_parameters
- init.sh
- lib/encoder.py
- lib/encoder_configuration.py
- lib/encoder_configuration_unittest.py
- lib/encoder_unittest.py
- lib/optimizer.py
- lib/optimizer_unittest.py
- lib/test_tools.py
This set of patches allows one to generate data from a combination of local results and imported results,
through the use of a search path to look up encoders and encodings from storage.
It also centralizes the interface between configuration of the encoders and the environment variables used to configure them.
> Config path integration

- lib/openh264.py
This allows the "rc" parameter to be varied in order to try different
styles of rate control.
Best results are achieved with -rc 2, which has no rate control, but
better compression.
> Adding "rc" as a parameter to openh264

- bin/run_all_tests
- lib/encoder.py
- lib/encoder_unittest.py
- lib/ffmpeg.py
- lib/file_codec.py
- lib/file_codec_unittest.py
- lib/hevc_jm.py
- lib/hevc_jm_unittest.py
- lib/openh264.py
- lib/openh264_unittest.py
- lib/vp8.py
- lib/vp8_unittest.py
- lib/vp9.py
- lib/vp9_unittest.py
- lib/x264.py
- lib/x264_unittest.py
- lib/x265.py
- lib/x265_unittest.py
This adds a field in the recorded results that gives a version string
for the encoder software used.
This is useful for keeping track of which results come from which
software version.
Fixes #68
> Add recording of a version number for encoder software.

- compile_tools.sh
- install_software.sh
Various scripts to counteract a year of bitrot.
- Drop the Travis linter. It now requires ruby-2.0, and "travis lint"
is the recommended way anyway.
- Update openh264 to 1.5.0. The checkout we used earlier disappeared.
- Modify install_software.sh to nuke depot_tools before reinstalling
> Update build scripts

- lib/fileset_picker.py
This is required to compute bd-rate differences for small videos, which was a specific request.
> Add rate targets for small videos

- bin/take_snapshot
- bin/verify_scores
- lib/encoder.py
- lib/encoder_unittest.py
- lib/optimizer.py
- lib/optimizer_unittest.py
Running calculations of scores & best scores over several directories
turned out to be complex if directory was passed as a call parameter.
This refactoring makes it part of the init parameters of the optimizer,
the context and the cache.
This means that one has to have functions for "adopting" an encoding
into the other context.
Fixes #77
> Refactoring the disk cache to have directory as an init parameter
